# Dockerfile for a Python App
FROM node:latest

#Install git
RUN apt-get update \        
     apt-get install -y git

#clone repo
RUN git clone https://github.com/spring-petclinic/spring-petclinic-angular.git
WORKDIR /spring-petclinic-angular

#install angular-cli
RUN npm install
RUN npm install -g @angular/cli@latest

#check


RUN pip3 install -r requirements.txt
EXPOSE 5000
ENTRYPOINT ["python3", "app.py"]