version: "3.8"
services:
#potentially dont need nginx
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf

  frontend:
    container_name: frontend
    #ADD image, build, UPDATE ports
    image: ${TAG}/frontend:latest
    build: 
    ports:
      - target: 8080
        published: 8080


  backend:
    container_name: backend
    #ADD image, build, UPDATE ports
    image: ${TAG}/backend:latest
    build:
    ports:
      - target: 9966
        published: 9966
