# Dockerfile for a Python App
FROM node:latest

#Install git
RUN apt-get update \        
     apt-get install -y git

#clone repo
RUN git clone https://github.com/spring-petclinic/spring-petclinic-rest.git
WORKDIR /spring-petclinic-rest

#install angular-cli
RUN npm install
RUN npm install -g @angular/cli@latest

#check
RUN ./mvnw spring-boot:run
EXPOSE 9966
